export enum HISTORY_TYPE {
  DEPOSIT = "DEPOSIT",
  WITHDRAW = "WITHDRAW",
  WEEKLY_COUPON = "WEEKLY_COUPON",
  OPTION_PAYOUT = "OPTION_PAYOUT",
  TRANSFER = "TRANSFER",
  COUPON_CREDIT = "[SuperHedge] Option Coupon Credit",
  OPTION_PROFIT_CREDIT = "[SuperHedge] Option Profit Credit",
  PRINCIPAL_CREDIT = "[SuperHedge] Principal Credit",
  EARLY_WITHDRAW = "EARLY WITHDRAW"
}

export enum WITHDRAW_TYPE {
  NONE = "NONE",
  PRINCIPAL = "PRINCIPAL",
  COUPON = "COUPON",
  OPTION = "OPTION",
}

export enum SUPPORT_CHAIN_IDS {
  GOERLI = 5,
  MOONBEAM_ALPHA = 1287,
  ARBITRUM_GOERLI = 421613,
  MANTLE_TESTNET = 5001,
  ARBITRUM = 42161
}
