# name: Backend - Build and Deploy - Dev

# on:
#   push:
#     branches:
#       - dev

# permissions:
#   id-token: write
#   contents: read
#   actions: write

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: SSH into server and pull code
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.DEV_DEPLOY_HOST }}
#           username: ${{ secrets.DEV_DEPLOY_USER }}
#           key: ${{ secrets.DEV_DEPLOY_SSH_KEY }}
#           port: ${{ secrets.DEV_DEPLOY_PORT }}
#           script: |
#             cd ${{ secrets.DEV_DEPLOY_TARGET }}
            
#             # Reset any local changes
#             git reset --hard
#             git clean -fd
            
#             # Pull latest code
#             git pull
            
#             # Clean up Docker
#             docker compose down
#             docker system prune -af
            
#             # Force rebuild and restart containers
#             docker compose build --no-cache
#             docker compose up -d
#             docker compose ps -a
            
#             echo "GITHUB_RUN_ID=${{ github.run_id }}" > .backend.github.env 
